CREATE DATABASE `interview`;

USE `interview`;

CREATE TABLE `interview`.`geography_columns` (
   `id` INT NOT NULL AUTO_INCREMENT,
   `table_name` VARCHAR(45) NOT NULL,
   `column_name` VARCHAR(45) NOT NULL,
   `city_name` VARCHAR(45) NOT NULL,
   `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`));

CREATE TABLE `interview`.`websites` (
   `id` INT NOT NULL AUTO_INCREMENT,
   `url` VARCHAR(45) NOT NULL,
   `status` VARCHAR(45) NOT NULL,
   `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`));